import { autocompletion } from "@codemirror/autocomplete";
import type { CompletionContext, CompletionResult } from "@codemirror/autocomplete";
import { linter } from "@codemirror/lint";
import type { EditorView } from "@codemirror/view";
import type { Diagnostic } from "@codemirror/lint";
import { Lexer } from "./lexer";
import { Parser } from "./parser";
import { lspKeywords } from "./lspKeywords";
import { KoreanConfig } from "./config";
import { message, syntaxError } from "./errs";

// Suggested keywords come from hana's language server tables (lspKeywords.ts is
// generated by `go run ./cmd/lspgen`), so the browser suggests what the server does.
const keywords: readonly string[] = [
  ...lspKeywords.keywords,
  ...lspKeywords.comparisons,
  ...lspKeywords.words,
];

export function hariCompletions(context: CompletionContext): CompletionResult | null {
  let word = context.matchBefore(/[\uAC00-\uD7A3a-zA-Z_]+/);
  let isVar = false;
  let isType = false;
  let isProp = false;
  let needsPrefixSpace = false;

  const varMatch = context.matchBefore(/'[\uAC00-\uD7A3a-zA-Z_]*/);
  const typeMatch = context.matchBefore(/\[[\uAC00-\uD7A3a-zA-Z_]*/);
  const propMatch = context.matchBefore(/<[\uAC00-\uD7A3a-zA-Z_]*/);
  const particleMatch = context.matchBefore(/의\s*$/);

  if (varMatch && (!word || varMatch.from < word.from)) { word = varMatch; isVar = true; }
  else if (typeMatch && (!word || typeMatch.from < word.from)) { word = typeMatch; isType = true; }
  else if (propMatch && (!word || propMatch.from < word.from)) { word = propMatch; isProp = true; }
  else if (particleMatch) {
    word = { from: context.pos, to: context.pos, text: "" };
    isProp = true;
    isVar = true;
    if (!particleMatch.text.match(/\s$/)) {
      needsPrefixSpace = true;
    }
  }

  if (!word) return null;
  if (word.from === word.to && !context.explicit && !particleMatch) return null;

  const doc = context.state.doc.toString();
  const options: any[] = [];
  const seen = new Set<string>();

  if (!isVar && !isType && !isProp) {
    for (const kw of keywords) {
      // For general keywords, if the user selects them, we can append a space to make typing smoother!
      // But only if it doesn't already have one? Actually just appending a space is nice for keywords like '만약', '출력하자'
      let applyStr = kw;
      if (["만약", "그렇지 않고", "그리고", "또는", "처음 만들어질 때", "돌려주는"].includes(kw)) {
        applyStr = kw + " ";
      } else if (["설계하자", "일단 해보자", "마무리는 항상", "그렇지 않다면"].includes(kw)) {
        applyStr = kw + ":\n    ";
      }
      options.push({ label: kw, type: "keyword", apply: applyStr });
    }
  }

  let tokens: any[] = [];
  try {
    const lexer = new Lexer(doc);
    tokens = lexer.tokens;
  } catch (e: any) {}

  const varRegex = /'([\uAC00-\uD7A3a-zA-Z0-9_]+)'/g;
  const typeRegex = /\[([\uAC00-\uD7A3a-zA-Z0-9_]+)\]/g;
  const propRegex = /<([\uAC00-\uD7A3a-zA-Z0-9_]+)>/g;
  
  let match;
  while ((match = varRegex.exec(doc)) !== null) {
    const val = "'" + match[1] + "'";
    if (!seen.has(val)) {
      seen.add(val);
      if (isVar || (!isType && !isProp)) options.push({ label: val, type: "variable", apply: (needsPrefixSpace ? " " : "") + val });
    }
  }
  while ((match = typeRegex.exec(doc)) !== null) {
    const val = "[" + match[1] + "]";
    if (!seen.has(val)) {
      seen.add(val);
      if (isType || (!isVar && !isProp)) options.push({ label: val, type: "class", apply: (needsPrefixSpace ? " " : "") + val });
    }
  }
  while ((match = propRegex.exec(doc)) !== null) {
    const val = "<" + match[1] + ">";
    if (!seen.has(val)) {
      seen.add(val);
      if (isProp || (!isVar && !isType)) options.push({ label: val, type: "method", apply: (needsPrefixSpace ? " " : "") + val });
    }
  }

  if (isProp || isVar) {
    const builtins = ["<자르기>", "<바꾸기>", "<분리하기>", "<포함확인>", "<추가하자>", "<꺼내자>"];
    for (const b of builtins) {
      if (!seen.has(b)) {
        seen.add(b);
        if (isProp) options.push({ label: b, type: "method", apply: (needsPrefixSpace ? " " : "") + b });
      }
    }
    if (isVar) {
      if (!seen.has("'길이'")) {
        seen.add("'길이'");
        options.push({ label: "'길이'", type: "variable", apply: (needsPrefixSpace ? " " : "") + "'길이'" });
      }
    }
  }

  return {
    from: word.from,
    options: options
  };
}

export const hariAutocomplete = autocompletion({ override: [hariCompletions] });

export const hariLintSource = (view: EditorView): Diagnostic[] => {
  let diagnostics: Diagnostic[] = [];
  const doc = view.state.doc.toString();
  
  if (!doc.trim()) return [];

  try {
    const lexer = new Lexer(doc);
    const parser = new Parser(lexer.tokens);
    parser.parseProgram();
    // The parser recovers from bad tokens, so it reports them as diagnostics
    // (same wording as hana's LSP and CLI, from the shared error catalog).
    for (const d of parser.diagnostics) {
      const line = Math.min(Math.max(d.line, 1), view.state.doc.lines);
      const info = view.state.doc.line(line);
      // Running off the end (empty literal) has no token: mark the line's last character.
      const from = d.literal === "" ? Math.max(info.to - 1, info.from) : Math.min(info.from + d.col, info.to);
      const to = d.literal === "" ? info.to : Math.min(from + Math.max(d.literal.length, 1), info.to);
      diagnostics.push({
        from,
        to: Math.max(to, from),
        severity: "error",
        message: message(KoreanConfig.locale, syntaxError(d)),
      });
    }
  } catch (err: any) {
    const msg = String(err);
    const match = msg.match(/(\d+)번째 줄(?:,\s*(\d+)번째 글자)?/);
    if (match) {
      let line = parseInt(match[1]);
      if (line < 1) line = 1;
      if (line > view.state.doc.lines) line = view.state.doc.lines;
      
      const col = match[2] ? parseInt(match[2]) : 0;
      
      const lineInfo = view.state.doc.line(line);
      const from = Math.min(lineInfo.from + col, lineInfo.to);
      const to = lineInfo.to;
      
      diagnostics.push({
        from: from,
        to: Math.max(from + 1, to),
        severity: "error",
        message: msg
      });
    } else {
        diagnostics.push({
          from: 0,
          to: view.state.doc.line(1).to,
          severity: "error",
          message: msg
        });
    }
  }
  
  return diagnostics;
};

export const hariLinter = linter(hariLintSource);
