// Code generated by `go run ./cmd/stdgen` from hana/std — DO NOT EDIT.
// Edit the name tables in hana/std and regenerate.

export interface StdModule {
  id: string;
  name: string;
  nativeOnly?: boolean;
  functions: readonly { id: string; name: string }[];
}

export const stdModules: readonly StdModule[] = [
  {
    id: "math",
    name: "수학",
    functions: [
      { id: "math.ceil", name: "올림" },
      { id: "math.floor", name: "버림" },
      { id: "math.sqrt", name: "제곱근" },
      { id: "math.pow", name: "거듭제곱" },
      { id: "math.abs", name: "절댓값" },
      { id: "math.round", name: "반올림" },
      { id: "math.sin", name: "사인" },
      { id: "math.cos", name: "코사인" },
      { id: "math.tan", name: "탄젠트" },
      { id: "math.log", name: "로그" },
      { id: "math.pi", name: "파이" },
      { id: "math.gcd", name: "최대공약수" },
      { id: "math.factorial", name: "팩토리얼" },
    ],
  },
  {
    id: "json",
    name: "JSON",
    functions: [
      { id: "json.parse", name: "파싱" },
      { id: "json.stringify", name: "문자열화" },
    ],
  },
  {
    id: "random",
    name: "무작위",
    functions: [
      { id: "random.float", name: "실수" },
      { id: "random.int", name: "정수" },
      { id: "random.choice", name: "고르기" },
      { id: "random.shuffle", name: "섞기" },
      { id: "random.uuid", name: "고유번호" },
    ],
  },
  {
    id: "datetime",
    name: "날짜",
    functions: [
      { id: "datetime.now", name: "지금" },
      { id: "datetime.format", name: "서식" },
      { id: "datetime.parse", name: "읽기" },
      { id: "datetime.weekday", name: "요일" },
      { id: "datetime.sleep", name: "기다리기" },
    ],
  },
  {
    id: "stats",
    name: "통계",
    functions: [
      { id: "stats.sum", name: "합계" },
      { id: "stats.min", name: "최솟값" },
      { id: "stats.max", name: "최댓값" },
      { id: "stats.mean", name: "평균" },
      { id: "stats.median", name: "중앙값" },
      { id: "stats.stdev", name: "표준편차" },
    ],
  },
  {
    id: "text",
    name: "텍스트",
    functions: [
      { id: "text.upper", name: "대문자" },
      { id: "text.lower", name: "소문자" },
      { id: "text.strip", name: "다듬기" },
      { id: "text.padleft", name: "왼쪽채우기" },
      { id: "text.padright", name: "오른쪽채우기" },
      { id: "text.repeat", name: "반복" },
      { id: "text.reverse", name: "거꾸로" },
      { id: "text.startswith", name: "시작하는지" },
      { id: "text.endswith", name: "끝나는지" },
      { id: "text.join", name: "잇기" },
      { id: "text.count", name: "세기" },
      { id: "text.find", name: "위치" },
    ],
  },
  {
    id: "list",
    name: "목록",
    functions: [
      { id: "list.sort", name: "정렬" },
      { id: "list.reverse", name: "뒤집기" },
      { id: "list.unique", name: "중복제거" },
      { id: "list.range", name: "범위" },
      { id: "list.flatten", name: "평탄화" },
      { id: "list.chunk", name: "조각내기" },
      { id: "list.zip", name: "짝짓기" },
    ],
  },
  {
    id: "encoding",
    name: "인코딩",
    functions: [
      { id: "encoding.base64encode", name: "베이스64인코딩" },
      { id: "encoding.base64decode", name: "베이스64디코딩" },
      { id: "encoding.urlencode", name: "주소인코딩" },
      { id: "encoding.urldecode", name: "주소디코딩" },
    ],
  },
  {
    id: "hash",
    name: "해시",
    functions: [
      { id: "hash.sha256", name: "SHA256" },
    ],
  },
  {
    id: "file",
    name: "파일",
    nativeOnly: true,
    functions: [
      { id: "file.read", name: "읽기" },
      { id: "file.lines", name: "줄읽기" },
      { id: "file.write", name: "쓰기" },
      { id: "file.append", name: "덧붙이기" },
      { id: "file.exists", name: "있는지" },
      { id: "file.isdir", name: "폴더인지" },
      { id: "file.delete", name: "지우기" },
      { id: "file.list", name: "목록" },
      { id: "file.mkdir", name: "폴더만들기" },
      { id: "file.move", name: "옮기기" },
    ],
  },
  {
    id: "path",
    name: "경로",
    functions: [
      { id: "path.join", name: "합치기" },
      { id: "path.dirname", name: "폴더이름" },
      { id: "path.basename", name: "파일이름" },
      { id: "path.ext", name: "확장자" },
      { id: "path.stem", name: "확장자뺀이름" },
      { id: "path.withext", name: "확장자바꾸기" },
      { id: "path.normalize", name: "정리하기" },
      { id: "path.isabs", name: "절대경로인지" },
      { id: "path.parts", name: "부분나누기" },
    ],
  },
  {
    id: "regex",
    name: "정규식",
    functions: [
      { id: "regex.test", name: "검사" },
      { id: "regex.find", name: "찾기" },
      { id: "regex.groups", name: "그룹" },
      { id: "regex.findall", name: "모두찾기" },
      { id: "regex.replace", name: "치환" },
      { id: "regex.split", name: "분할" },
    ],
  },
];
