// Code generated by `go run ./cmd/stdgen` from hana/std — DO NOT EDIT.
// Edit the name tables in hana/std and regenerate.

export const stdModules = [
  {
    id: "math",
    name: "수학",
    functions: [
      { id: "math.ceil", name: "올림" },
      { id: "math.floor", name: "버림" },
    ],
  },
] as const;
